version: '3.9'

services:
  # 1. База для пользователей и метаданных (client-service)
  postgres-client:
    image: postgres:16-alpine
    container_name: studytube-db-client
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: client_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d client_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - studytube-network

  # 2. База для Саммари и Векторов (ai-service)
  postgres-ai:
    image: pgvector/pgvector:pg16
    container_name: studytube-db-ai
    restart: always
    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
      POSTGRES_DB: ai_db
    ports:
      - "5433:5432" # Пробрасываем на другой порт хоста, чтобы не конфликтовать с 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - studytube-network

  redis:
    image: redis:7-alpine
    container_name: studytube-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - studytube-network

  frontend:
    build: ./frontend
    container_name: studytube-frontend
    restart: always
    expose:
      - "3000"
    networks:
      - studytube-network

  client-service:
    build: ./client-service
    container_name: studytube-client
    restart: always
    depends_on:
      postgres-client:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-client:5432/client_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=z6B87106967527068564020358d7c6246473c217436214578912345678901234
    networks:
      - studytube-network

  ai-service:
    build: ./ai-service
    container_name: studytube-ai
    restart: always
    depends_on:
      postgres-ai:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ai:5432/ai_db
      - SPRING_DATASOURCE_USERNAME=ai_user
      - SPRING_DATASOURCE_PASSWORD=ai_password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_AI_OLLAMA_BASE_URL=http://host.docker.internal:11434
      - JWT_SECRET=z6B87106967527068564020358d7c6246473c217436214578912345678901234
      - JWT_EXPIRATION=86400000
    networks:
      - studytube-network
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: studytube-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - client-service
      - ai-service
      - frontend
    networks:
      - studytube-network

networks:
  studytube-network:
    driver: bridge