server:
  port: 8081
spring:
  application:
    name: ai-service

  # Настройки Postgres (для хранения Саммари)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://studytube-db-ai:5432/ai_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Поменял на update, чтобы не терять данные при каждом запуске
    show-sql: true

  # Настройки Redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:studytube-redis}
      port: 6379

  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4o-mini # Идеально для саммари: дешево и быстро
          temperature: 0.7

# Безопасность
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}